// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yddnpfovsusufqlejzry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkZG5wZm92c3VzdWZxbGVqenJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDcxNzgsImV4cCI6MjA2MDI4MzE3OH0.WSXtvyHaOR2pPzIVJzMj2dKvmMKw-gdszQdcKKli4Lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);